# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-chaserelock-github-io'

# google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/chaserelock'}
- {icon: 'twitter', link: 'https://twitter.com/yeslikethebank'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/chase-relock-b0146544/'}
- {icon: 'envelope', link: 'mailto:chase.relock@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
